export type CountryItem = { code: string; name: string };

// ISO 3166-1 alpha-2 subset (extendable). Names localized by i18n in UI; here kept in Russian for now.
export const COUNTRIES_FULL: CountryItem[] = [
  { code: 'AE', name: 'ОАЭ' },
  { code: 'AF', name: 'Афганистан' },
  { code: 'AL', name: 'Албания' },
  { code: 'AM', name: 'Армения' },
  { code: 'AO', name: 'Ангола' },
  { code: 'AR', name: 'Аргентина' },
  { code: 'AT', name: 'Австрия' },
  { code: 'AU', name: 'Австралия' },
  { code: 'AZ', name: 'Азербайджан' },
  { code: 'BA', name: 'Босния и Герцеговина' },
  { code: 'BD', name: 'Бангладеш' },
  { code: 'BE', name: 'Бельгия' },
  { code: 'BG', name: 'Болгария' },
  { code: 'BH', name: 'Бахрейн' },
  { code: 'BR', name: 'Бразилия' },
  { code: 'BY', name: 'Беларусь' },
  { code: 'CA', name: 'Канада' },
  { code: 'CH', name: 'Швейцария' },
  { code: 'CL', name: 'Чили' },
  { code: 'CN', name: 'Китай' },
  { code: 'CZ', name: 'Чехия' },
  { code: 'DE', name: 'Германия' },
  { code: 'DK', name: 'Дания' },
  { code: 'DZ', name: 'Алжир' },
  { code: 'EE', name: 'Эстония' },
  { code: 'EG', name: 'Египет' },
  { code: 'ES', name: 'Испания' },
  { code: 'FI', name: 'Финляндия' },
  { code: 'FR', name: 'Франция' },
  { code: 'GB', name: 'Великобритания' },
  { code: 'GE', name: 'Грузия' },
  { code: 'GR', name: 'Греция' },
  { code: 'HR', name: 'Хорватия' },
  { code: 'HU', name: 'Венгрия' },
  { code: 'IE', name: 'Ирландия' },
  { code: 'IL', name: 'Израиль' },
  { code: 'IN', name: 'Индия' },
  { code: 'IQ', name: 'Ирак' },
  { code: 'IR', name: 'Иран' },
  { code: 'IS', name: 'Исландия' },
  { code: 'IT', name: 'Италия' },
  { code: 'JP', name: 'Япония' },
  { code: 'JO', name: 'Иордания' },
  { code: 'KZ', name: 'Казахстан' },
  { code: 'KG', name: 'Киргизия' },
  { code: 'KH', name: 'Камбоджа' },
  { code: 'KR', name: 'Южная Корея' },
  { code: 'KW', name: 'Кувейт' },
  { code: 'LB', name: 'Ливан' },
  { code: 'LT', name: 'Литва' },
  { code: 'LV', name: 'Латвия' },
  { code: 'MD', name: 'Молдова' },
  { code: 'ME', name: 'Черногория' },
  { code: 'MK', name: 'Северная Македония' },
  { code: 'MX', name: 'Мексика' },
  { code: 'MY', name: 'Малайзия' },
  { code: 'NL', name: 'Нидерланды' },
  { code: 'NO', name: 'Норвегия' },
  { code: 'NZ', name: 'Новая Зеландия' },
  { code: 'PL', name: 'Польша' },
  { code: 'PT', name: 'Португалия' },
  { code: 'QA', name: 'Катар' },
  { code: 'RO', name: 'Румыния' },
  { code: 'RS', name: 'Сербия' },
  { code: 'RU', name: 'Россия' },
  { code: 'SA', name: 'Саудовская Аравия' },
  { code: 'SE', name: 'Швеция' },
  { code: 'SG', name: 'Сингапур' },
  { code: 'SI', name: 'Словения' },
  { code: 'SK', name: 'Словакия' },
  { code: 'TH', name: 'Таиланд' },
  { code: 'TJ', name: 'Таджикистан' },
  { code: 'TM', name: 'Туркменистан' },
  { code: 'TR', name: 'Турция' },
  { code: 'UA', name: 'Украина' },
  { code: 'US', name: 'США' },
  { code: 'UZ', name: 'Узбекистан' },
  { code: 'VN', name: 'Вьетнам' },
];


