import { StyleSheet } from 'react-native';
import { getCurrentColors, SHADOWS, SIZES } from '../../constants/colors';

export const createMapViewStyles = (isDark: boolean) => {
  const palette = getCurrentColors(isDark);

  return StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: palette.background,
    },
    map: {
      flex: 1,
      backgroundColor: palette.surface,
    },
    expandButton: {
      position: 'absolute',
      bottom: SIZES.lg,
      right: SIZES.lg,
      width: 48,
      height: 48,
      borderRadius: 24,
      backgroundColor: palette.card,
      alignItems: 'center',
      justifyContent: 'center',
      borderWidth: 1,
      borderColor: palette.border,
      ...(isDark ? SHADOWS.dark.medium : SHADOWS.light.medium),
    },
    expandButtonContainer: {
      position: 'absolute',
      bottom: SIZES.lg,
      right: SIZES.lg,
      alignItems: 'flex-end',
    },
    additionalButtonsContainer: {
      position: 'absolute',
      bottom: SIZES.lg + 70,
      right: SIZES.lg - 4,
      alignItems: 'flex-end',
    },
    additionalButton: {
      width: 40,
      height: 40,
      borderRadius: 20,
      backgroundColor: palette.card,
      alignItems: 'center',
      justifyContent: 'center',
      borderWidth: 1,
      borderColor: palette.border,
      marginBottom: SIZES.sm,
      marginRight: SIZES.lg + 6,
      ...(isDark ? SHADOWS.dark.medium : SHADOWS.light.medium),
    },
    markerAContainer: {
      backgroundColor: palette.card,
      borderRadius: 16,
      borderWidth: 2,
      borderColor: isDark ? palette.borderLight : '#222',
      padding: 2,
      alignItems: 'center',
      justifyContent: 'center',
      ...(isDark ? SHADOWS.dark.small : SHADOWS.light.small),
    },
    markerBContainer: {
      backgroundColor: palette.card,
      borderRadius: 16,
      borderWidth: 2,
      borderColor: palette.success,
      padding: 2,
      alignItems: 'center',
      justifyContent: 'center',
      ...(isDark ? SHADOWS.dark.small : SHADOWS.light.small),
    },
    driverMarkerContainer: {
      backgroundColor: palette.primary,
      borderRadius: 20,
      width: 40,
      height: 40,
      alignItems: 'center',
      justifyContent: 'center',
      borderWidth: 3,
      borderColor: '#FFFFFF',
      ...(isDark ? SHADOWS.dark.medium : SHADOWS.light.medium),
    },
    durationMarkerContainer: {
      backgroundColor: palette.text,
      borderRadius: 12,
      paddingHorizontal: 8,
      paddingVertical: 4,
      borderWidth: 2,
      borderColor: '#fff',
      ...(isDark ? SHADOWS.dark.medium : SHADOWS.light.medium),
    },
    durationMarkerText: {
      color: '#fff',
      fontSize: 12,
      fontWeight: '600',
    },
    // Driver Item Styles
    driverItem: {
      flexDirection: 'column',
      marginBottom: SIZES.lg,
      marginHorizontal: SIZES.xl,
      paddingHorizontal: SIZES.lg,
      paddingVertical: SIZES.lg + 4,
      borderRadius: SIZES.radius.lg + 2,
      backgroundColor: palette.surface,
      borderWidth: 1,
      borderColor: palette.border,
      ...(isDark ? SHADOWS.dark.medium : SHADOWS.light.medium),
      alignSelf: 'stretch',
      flex: 0,
      width: undefined,
      height: undefined,
    },
    driverHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      marginBottom: SIZES.lg + 6,
      paddingBottom: SIZES.md + 6,
      borderBottomWidth: 1,
      borderBottomColor: palette.border,
    },
    avatarContainer: {
      position: 'relative',
    },
    avatar: {
      width: 48,
      height: 48,
      borderRadius: 24,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: palette.primary,
    },
    onlineIndicator: {
      position: 'absolute',
      bottom: 2,
      right: 2,
      width: 12,
      height: 12,
      borderRadius: 6,
      backgroundColor: '#10B981',
      borderWidth: 2,
      borderColor: palette.background,
    },
    driverMainInfo: {
      flex: 1,
      marginLeft: SIZES.md,
    },
    nameContainer: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: SIZES.xs,
    },
    favoriteIcon: {
      marginLeft: SIZES.xs,
    },
    nameRatingRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
    },
    driverName: {
      fontSize: SIZES.fontSize.md,
      fontWeight: '600',
      color: palette.text,
      flexShrink: 1,
    },
    ratingText: {
      fontSize: SIZES.fontSize.md,
      fontWeight: '600',
      color: palette.primary,
    },
    vehicleExpandRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginTop: 2,
    },
    vehicleInfo: {
      fontSize: SIZES.fontSize.sm,
      color: palette.textSecondary,
      fontWeight: '500',
    },
    vehicleInfoContainer: {
      flexDirection: 'column',
      alignItems: 'flex-start',
    },
    vehicleNumber: {
      fontSize: SIZES.fontSize.sm,
      color: palette.textSecondary,
      fontWeight: '500',
      marginTop: 2,
    },
    vehiclePhotoContainer: {
      width: 120,
      height: 100,
      borderRadius: 8,
      backgroundColor: palette.surface,
      marginLeft: SIZES.sm,
    },
    vehiclePhoto: {
      width: '70%',
      height: '70%',
      alignSelf: 'center',
      marginTop: '15%',
    },
    vehiclePhotoPlaceholder: {
      width: '100%',
      height: '100%',
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: palette.surface,
    },
    driverExpandButton: {
      padding: 8,
      marginLeft: SIZES.xs,
      borderRadius: SIZES.radius.sm,
      backgroundColor: 'transparent',
    },
    driverInfoBar: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginTop: -SIZES.lg - 4,
      marginBottom: SIZES.xs + 6,
      paddingHorizontal: SIZES.sm,
      paddingVertical: SIZES.xs + 6,
      borderBottomWidth: 1,
      borderBottomColor: palette.border,
    },
    scheduleInfo: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: SIZES.xs,
    },
    scheduleText: {
      fontSize: SIZES.fontSize.sm,
      color: palette.textSecondary,
      fontWeight: '500',
    },
    premiumInfo: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: SIZES.xs,
    },
    premiumText: {
      fontSize: SIZES.fontSize.sm,
      color: palette.textSecondary,
      fontWeight: '500',
    },
    stopsInfo: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: SIZES.xs / 2,
    },
    stopsText: {
      fontSize: SIZES.fontSize.sm,
      color: palette.textSecondary,
      fontWeight: '500',
    },
    ballInfo: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: SIZES.xs,
    },
    ballText: {
      fontSize: SIZES.fontSize.sm,
      color: palette.textSecondary,
      fontWeight: '500',
    },
    expandableContent: {
      overflow: 'hidden',
    },
    tripsContainer: {
      marginVertical: SIZES.xs + 6,
    },
    tripItem: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingVertical: SIZES.xs + 6,
    },
    tripDot: {
      width: 8,
      height: 8,
      borderRadius: 4,
      backgroundColor: '#10B981',
      marginRight: SIZES.md,
    },
    tripDotBlue: {
      backgroundColor: '#3B82F6',
    },
    tripDotLocation: {
      backgroundColor: 'transparent',
      borderWidth: 2,
      borderColor: '#6B7280',
    },
    tripText: {
      flex: 1,
      fontSize: SIZES.fontSize.md,
      color: palette.text,
      fontWeight: '500',
    },
    tripTime: {
      fontSize: SIZES.fontSize.md,
      color: palette.textSecondary,
      fontWeight: '500',
    },
    bottomBorder: {
      marginTop: SIZES.xs + 6,
      paddingTop: SIZES.xs + 6,
      borderTopWidth: 1,
      borderTopColor: palette.border,
    },
    buttonsContainer: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginTop: SIZES.md,
      gap: SIZES.md,
    },
    leftButton: {
      flex: 1,
      backgroundColor: palette.primary,
      paddingVertical: SIZES.md,
      paddingHorizontal: SIZES.md,
      borderRadius: SIZES.radius.md,
      alignItems: 'center',
      justifyContent: 'center',
    },
    buttonContent: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: SIZES.xs,
    },
    leftButtonText: {
      color: '#FFFFFF',
      fontSize: SIZES.fontSize.md,
      fontWeight: '600',
    },
    rightButton: {
      flex: 1,
      backgroundColor: 'transparent',
      paddingVertical: SIZES.md,
      paddingHorizontal: SIZES.md,
      borderRadius: SIZES.radius.md,
      borderWidth: 1,
      borderColor: palette.border,
      alignItems: 'center',
      justifyContent: 'center',
    },
    rightButtonContent: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: SIZES.xs,
    },
    rightButtonText: {
      color: palette.text,
      fontSize: SIZES.fontSize.md,
      fontWeight: '600',
    },
  });
};

// Backward-compatible default (light theme)
export const MapViewStyles = createMapViewStyles(false);