import { StyleSheet } from "react-native";

export const SelectStyles = StyleSheet.create({
  container: {
    borderWidth: 1,
    borderColor: "#E5E7EB",
    borderRadius: 8,
    backgroundColor: "#fff",
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  label: {
    fontSize: 14,
    color: "#6B7280",
    marginBottom: 4,
  },
  picker: {
    fontSize: 16,
    color: "#111827",
  },
  error: {
    color: "#EF4444",
    fontSize: 12,
    marginTop: 4,
  },
  select: {
    borderWidth: 1.5,
    borderRadius: 16,
    paddingHorizontal: 18,
    paddingVertical: 16,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    minHeight: 56,
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 4,
    backgroundColor: "#ffffff",
  },
  selectText: {
    fontSize: 16,
    fontWeight: "500",
    flex: 1,
    color: "#374151",
    letterSpacing: 0.1,
  },
  required: {
    color: "#DC2626",
  },
  overlay: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.15)",
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: 20,
    paddingVertical: 20,
    zIndex: 3000,
    elevation: 3000,
  },
  dropdown: {
    backgroundColor: "#fff",
    borderRadius: 20,
    padding: 20,
    width: "95%",
    minHeight: 140,
    maxHeight: 400,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.15,
    shadowRadius: 24,
    elevation: 12,
    zIndex: 3001,
    borderWidth: 1,
    borderColor: "rgba(0,0,0,0.05)",
  },
  dropdownCompact: {
    height: "auto",
    maxHeight: 300,
    borderRadius: 16,
  },
  searchContainer: {
    padding: 16,
    borderBottomWidth: 1,
    borderBottomColor: "rgba(229, 231, 235, 0.3)",
  },
  searchInput: {
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderRadius: 12,
    fontSize: 16,
    borderWidth: 1,
    borderColor: "rgba(229, 231, 235, 0.5)",
  },
  optionsList: {
    flex: 1,
    paddingHorizontal: 8,
  },
  optionsListCompact: {
    flex: 0,
    paddingVertical: 8,
  },
  option: {
    backgroundColor: "#fff",
    borderRadius: 14,
    marginVertical: 6,
    marginHorizontal: 4,
    paddingVertical: 16,
    paddingHorizontal: 18,
    borderWidth: 1.5,
    borderColor: "#f3f4f6",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 2,
    elevation: 1,
  },
  optionSelected: {
    backgroundColor: "#003366",
    borderColor: "#003366",
    shadowColor: "#003366",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 3,
  },
  optionCompact: {
    paddingVertical: 20,
    marginVertical: 6,
    marginHorizontal: 8,
    borderRadius: 18,
  },
  optionContent: {
    flexDirection: "row",
    alignItems: "center",
    flex: 1,
  },
  optionIcon: {
    marginRight: 12,
  },
  optionIconCompact: {
    marginRight: 16,
  },
  optionText: {
    color: "#374151",
    fontWeight: "600",
    fontSize: 16,
    letterSpacing: 0.2,
  },
  optionTextSelected: {
    color: "#ffffff",
    fontWeight: "700",
    letterSpacing: 0.3,
  },
});
