import { StyleSheet } from "react-native";

export const SocialAuthButtonsStyles = StyleSheet.create({
  container: {
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    gap: 16,
  },
  googleButton: {
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: "#fff",
    alignItems: "center",
    justifyContent: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
    borderWidth: 1,
    borderColor: "#E5E7EB",
  },
  googleText: {
    marginLeft: 12,
    fontSize: 16,
    color: "#374151",
  },
  facebookButton: {
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: "#1877F2",
    alignItems: "center",
    justifyContent: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  facebookText: {
    marginLeft: 12,
    fontSize: 16,
    color: "#FFFFFF",
  },
  appleButton: {
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: "#000",
    alignItems: "center",
    justifyContent: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  appleText: {
    marginLeft: 12,
    fontSize: 16,
    color: "#FFFFFF",
  },
});
