import { StyleSheet } from 'react-native';

export const createMapScreenStyles = (isDark: boolean) => StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: isDark ? '#1F2937' : '#FFFFFF',
  },
  header: {
    padding: 20,
    paddingTop: 40,
    alignItems: 'center',
  },
  title: {
    fontSize: 24,
    fontWeight: 'bold',
    color: isDark ? '#F9FAFB' : '#111827',
    marginBottom: 8,
  },
  subtitle: {
    fontSize: 16,
    color: isDark ? '#9CA3AF' : '#6B7280',
  },
  mapContainer: {
    flex: 1,
    margin: 20,
    borderRadius: 16,
    overflow: 'hidden',
    backgroundColor: isDark ? '#374151' : '#F3F4F6',
    position: 'relative',
  },
  mapPlaceholder: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
  },
  mapPlaceholderText: {
    fontSize: 48,
    marginBottom: 16,
  },
  mapPlaceholderSubtext: {
    fontSize: 16,
    color: isDark ? '#9CA3AF' : '#6B7280',
    textAlign: 'center',
    marginBottom: 20,
  },
  statusInfo: {
    backgroundColor: isDark ? '#4B5563' : '#E5E7EB',
    padding: 16,
    borderRadius: 12,
    width: '100%',
  },
  statusText: {
    fontSize: 14,
    color: isDark ? '#D1D5DB' : '#374151',
    marginBottom: 4,
  },
  controlButtonText: {
    fontSize: 20,
  },
  infoPanel: {
    margin: 20,
    padding: 16,
    backgroundColor: isDark ? '#374151' : '#F3F4F6',
    borderRadius: 12,
  },
  infoTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: isDark ? '#F9FAFB' : '#111827',
    marginBottom: 12,
  },
  infoText: {
    fontSize: 14,
    color: isDark ? '#D1D5DB' : '#374151',
    marginBottom: 6,
  },
  actionButtons: {
    flexDirection: 'row',
    gap: 12,
    margin: 20,
    marginBottom: 40,
  },
  actionButton: {
    flex: 1,
    padding: 16,
    backgroundColor: isDark ? '#DC2626' : '#EF4444',
    borderRadius: 12,
    alignItems: 'center',
  },
  actionButtonText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '600',
  },
  
  // MapControls styles
  controlsContainer: {
    position: 'absolute',
    right: 16,
    top: 16,
    gap: 12,
  },
  settingsPanel: {
    position: 'absolute',
    right: 0,
    top: 0,
    backgroundColor: isDark ? '#4B5563' : '#FFFFFF',
    borderRadius: 8,
    padding: 8,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  settingsButton: {
    width: 40,
    height: 40,
    justifyContent: 'center',
    alignItems: 'center',
  },
  mainControls: {
    gap: 8,
  },
  controlButton: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: isDark ? '#4B5563' : '#FFFFFF',
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  controlButtonActive: {
    backgroundColor: isDark ? '#3B82F6' : '#3B82F6',
  },
  zoomControls: {
    gap: 4,
  },
  zoomButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: isDark ? '#4B5563' : '#FFFFFF',
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  locateButton: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: isDark ? '#4B5563' : '#FFFFFF',
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  
  // Modal styles
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  
  // ReportModal styles
  reportModalContainer: {
    width: '90%',
    maxWidth: 400,
    backgroundColor: isDark ? '#374151' : '#FFFFFF',
    borderRadius: 16,
    padding: 20,
  },
  reportModalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 16,
  },
  reportModalTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: isDark ? '#F9FAFB' : '#111827',
  },
  closeButton: {
    width: 32,
    height: 32,
    justifyContent: 'center',
    alignItems: 'center',
  },
  reportModalContent: {
    marginBottom: 20,
  },
  reportModalDescription: {
    fontSize: 14,
    color: isDark ? '#D1D5DB' : '#374151',
    marginBottom: 12,
  },
  reportTextInput: {
    borderWidth: 1,
    borderColor: isDark ? '#4B5563' : '#D1D5DB',
    borderRadius: 8,
    padding: 12,
    fontSize: 14,
    color: isDark ? '#F9FAFB' : '#111827',
    backgroundColor: isDark ? '#4B5563' : '#F9FAFB',
    minHeight: 80,
  },
  reportModalActions: {
    flexDirection: 'row',
    gap: 12,
  },
  reportButton: {
    flex: 1,
    padding: 12,
    borderRadius: 8,
    alignItems: 'center',
  },
  cancelButton: {
    backgroundColor: isDark ? '#4B5563' : '#E5E7EB',
  },
  submitButton: {
    backgroundColor: '#3B82F6',
  },
  cancelButtonText: {
    color: isDark ? '#D1D5DB' : '#374151',
    fontSize: 14,
    fontWeight: '500',
  },
  submitButtonText: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '500',
  },
  
  // SimpleDialog styles
  simpleDialogContainer: {
    width: '90%',
    maxWidth: 350,
    backgroundColor: isDark ? '#374151' : '#FFFFFF',
    borderRadius: 16,
    padding: 20,
  },
  simpleDialogHeader: {
    marginBottom: 16,
  },
  simpleDialogTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: isDark ? '#F9FAFB' : '#111827',
    textAlign: 'center',
  },
  simpleDialogContent: {
    marginBottom: 20,
  },
  simpleDialogMessage: {
    fontSize: 14,
    color: isDark ? '#D1D5DB' : '#374151',
    textAlign: 'center',
    lineHeight: 20,
  },
  simpleDialogActions: {
    flexDirection: 'row',
    gap: 12,
  },
  dialogButton: {
    flex: 1,
    padding: 12,
    borderRadius: 8,
    alignItems: 'center',
  },
  noButton: {
    backgroundColor: isDark ? '#4B5563' : '#E5E7EB',
  },
  yesButton: {
    backgroundColor: '#EF4444',
  },
  noButtonText: {
    color: isDark ? '#D1D5DB' : '#374151',
    fontSize: 14,
    fontWeight: '500',
  },
  yesButtonText: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '500',
  },
  
  // MapControls styles
  topLeftButton: {
    position: 'absolute',
    top: 50,
    left: 20,
    zIndex: 1000,
  },
  topRightButton: {
    position: 'absolute',
    top: 50,
    right: 20,
    zIndex: 1000,
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: isDark ? '#374151' : '#F3F4F6',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  bottomButtonsContainer: {
    position: 'absolute',
    bottom: 100,
    right: 20,
    zIndex: 1000,
  },
  bottomButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: isDark ? '#374151' : '#F3F4F6',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 10,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  leftButton: {
    position: 'absolute',
    bottom: 100,
    left: 20,
    zIndex: 1000,
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: isDark ? '#374151' : '#F3F4F6',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
});
