import { StyleSheet, Platform } from 'react-native';
import { adaptiveColors, adaptiveSizes } from '../../../../../../shared/constants/adaptiveConstants';

/**
 * Chat Screen Styles
 * 
 * Centralized styles for chat screen components
 * Uses adaptive constants for consistent theming
 */

export const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    marginHorizontal: adaptiveSizes.spacing.lg,
    paddingHorizontal: adaptiveSizes.spacing.lg,
    paddingVertical: adaptiveSizes.spacing.md,
    borderBottomWidth: 1,
    borderBottomColor: adaptiveColors.border,
    borderRadius: adaptiveSizes.borderRadius.lg,
    overflow: 'hidden',
    shadowColor: adaptiveColors.shadow,
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  headerAvatar: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: adaptiveColors.primary,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: adaptiveSizes.spacing.md,
    position: 'relative',
  },
  headerOnlineIndicator: {
    position: 'absolute',
    bottom: 0,
    right: 0,
    width: 12,
    height: 12,
    borderRadius: 6,
    backgroundColor: '#10B981',
    borderWidth: 2,
    borderColor: adaptiveColors.background,
  },
  headerOfflineIndicator: {
    position: 'absolute',
    bottom: 0,
    right: 0,
    width: 12,
    height: 12,
    borderRadius: 6,
    backgroundColor: '#9CA3AF',
    borderWidth: 2,
    borderColor: adaptiveColors.background,
  },
  headerInfo: {
    flex: 1,
  },
  headerName: {
    fontSize: adaptiveSizes.font.lg,
    fontWeight: '600',
  },
  headerStatus: {
    fontSize: adaptiveSizes.font.sm,
    marginTop: 2,
  },
  headerActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: adaptiveSizes.spacing.sm,
  },
  headerButton: {
    padding: adaptiveSizes.spacing.sm,
    borderRadius: adaptiveSizes.borderRadius.md,
  },
  messagesContent: {
    paddingHorizontal: adaptiveSizes.spacing.lg,
    paddingVertical: adaptiveSizes.spacing.md,
    flexGrow: 1,
  },
  messageContainer: {
    marginVertical: adaptiveSizes.spacing.sm,
    flexDirection: 'row',
    alignItems: 'flex-end',
  },
  userMessage: {
    justifyContent: 'flex-end',
  },
  clientMessage: {
    justifyContent: 'flex-start',
  },
  messageAvatar: {
    width: 32,
    height: 32,
    borderRadius: 16,
    marginRight: adaptiveSizes.spacing.sm,
    alignItems: 'center',
    justifyContent: 'center',
  },
  messageBubble: {
    maxWidth: '80%',
    borderRadius: adaptiveSizes.borderRadius.lg,
    paddingHorizontal: adaptiveSizes.spacing.lg,
    paddingVertical: adaptiveSizes.spacing.md,
    ...Platform.select({
      ios: {
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.1,
        shadowRadius: 3,
      },
      android: {
        elevation: 3,
      },
    }),
  },
  messageText: {
    fontSize: adaptiveSizes.font.md,
    lineHeight: 20,
  },
  otherMessage: {
    borderWidth: 1,
    borderColor: adaptiveColors.border,
  },
  otherMessageText: {
    // Color will be set dynamically
  },
  messageTime: {
    fontSize: adaptiveSizes.font.xs,
    marginTop: adaptiveSizes.spacing.xs,
    alignSelf: 'flex-end',
  },
  messageStatus: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: adaptiveSizes.spacing.xs,
    alignSelf: 'flex-end',
  },
  statusIcon: {
    marginLeft: adaptiveSizes.spacing.xs,
  },
  inputAvoider: {
    backgroundColor: 'transparent',
  },
  inputContainer: {
    marginHorizontal: adaptiveSizes.spacing.lg,
    marginBottom: adaptiveSizes.spacing.md,
    paddingHorizontal: adaptiveSizes.spacing.lg,
    paddingTop: adaptiveSizes.spacing.sm,
    paddingBottom: Platform.OS === 'ios' ? adaptiveSizes.spacing.lg : adaptiveSizes.spacing.sm,
    borderWidth: 1,
    borderColor: adaptiveColors.border,
    borderRadius: adaptiveSizes.borderRadius.lg,
    shadowColor: adaptiveColors.shadow,
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  inputRow: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    gap: adaptiveSizes.spacing.sm,
  },
  toolbarButton: {
    width: 44,
    height: 44,
    borderRadius: 22,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: adaptiveColors.background,
    borderWidth: 1,
    borderColor: adaptiveColors.border,
  },
  textInput: {
    flex: 1,
    borderRadius: 22,
    paddingHorizontal: adaptiveSizes.spacing.lg,
    paddingVertical: adaptiveSizes.spacing.md,
    fontSize: adaptiveSizes.font.md,
    maxHeight: 120,
    minHeight: 44,
    borderWidth: 1,
    borderColor: adaptiveColors.border,
  },
  sendButton: {
    width: 44,
    height: 44,
    borderRadius: 22,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: adaptiveColors.primary,
    shadowColor: adaptiveColors.shadow,
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  attachmentMenu: {
    position: 'absolute',
    bottom: 80,
    left: 0,
    borderRadius: adaptiveSizes.borderRadius.lg,
    borderWidth: 1,
    borderColor: adaptiveColors.border,
    padding: adaptiveSizes.spacing.sm,
    shadowColor: adaptiveColors.shadow,
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.2,
    shadowRadius: 8,
    elevation: 8,
  },
  attachmentOption: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: adaptiveSizes.spacing.sm,
    paddingHorizontal: adaptiveSizes.spacing.md,
    borderRadius: adaptiveSizes.borderRadius.md,
  },
  attachmentOptionText: {
    marginLeft: adaptiveSizes.spacing.sm,
    fontSize: adaptiveSizes.font.md,
  },
  // Sheet styles
  callSheetOverlay: {
    position: 'absolute',
    left: 0,
    right: 0,
    top: 0,
    bottom: 0,
    justifyContent: 'flex-end',
  },
  callSheetBackdrop: {
    position: 'absolute',
    left: 0,
    right: 0,
    top: 0,
    bottom: 0,
    backgroundColor: 'rgba(0,0,0,0.4)',
  },
  callSheetContainer: {
    borderTopLeftRadius: adaptiveSizes.borderRadius.xl,
    borderTopRightRadius: adaptiveSizes.borderRadius.xl,
    borderWidth: 1,
    borderColor: adaptiveColors.border,
    paddingHorizontal: adaptiveSizes.spacing.lg,
    paddingTop: adaptiveSizes.spacing.md,
    paddingBottom: adaptiveSizes.spacing.xl,
    shadowColor: adaptiveColors.shadow,
    shadowOffset: {
      width: 0,
      height: 8,
    },
    shadowOpacity: 0.3,
    shadowRadius: 16,
    elevation: 16,
  },
  callSheetClose: {
    position: 'absolute',
    top: adaptiveSizes.spacing.md,
    right: adaptiveSizes.spacing.md,
    padding: adaptiveSizes.spacing.sm,
    borderRadius: adaptiveSizes.borderRadius.md,
  },
  callSheetHandle: {
    alignSelf: 'center',
    width: 40,
    height: 4,
    borderRadius: 2,
    marginBottom: adaptiveSizes.spacing.md,
  },
  callSheetTitle: {
    fontSize: adaptiveSizes.font.xl,
    fontWeight: '600',
    marginBottom: adaptiveSizes.spacing.md,
    textAlign: 'center',
  },
  callSheetOption: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: adaptiveSizes.spacing.md,
    backgroundColor: adaptiveColors.background,
    borderRadius: adaptiveSizes.borderRadius.lg,
    paddingHorizontal: adaptiveSizes.spacing.lg,
    paddingVertical: adaptiveSizes.spacing.md,
    borderWidth: 1,
    borderColor: adaptiveColors.border,
    marginTop: adaptiveSizes.spacing.sm,
  },
  callSheetOptionText: {
    fontSize: adaptiveSizes.font.md,
  },
  // Profile sheet styles
  profileHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: adaptiveSizes.spacing.md,
    paddingHorizontal: adaptiveSizes.spacing.sm,
    marginTop: adaptiveSizes.spacing.md,
    marginBottom: adaptiveSizes.spacing.md,
  },
  profileAvatarLarge: {
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: adaptiveColors.primary,
    alignItems: 'center',
    justifyContent: 'center',
    position: 'relative',
  },
  profileInfo: {
    flex: 1,
  },
  profileNameRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: adaptiveSizes.spacing.md,
  },
  profileName: {
    fontSize: adaptiveSizes.font.xl,
    fontWeight: '700',
    marginBottom: 2,
  },
  profileSubline: {
    fontSize: adaptiveSizes.font.md,
  },
  profileRating: {
    paddingHorizontal: adaptiveSizes.spacing.sm,
    paddingVertical: adaptiveSizes.spacing.xs,
    borderRadius: adaptiveSizes.borderRadius.md,
    backgroundColor: '#10B9811A',
    alignSelf: 'flex-start',
  },
  profileRatingText: {
    color: '#10B981',
    fontWeight: '700',
    fontSize: adaptiveSizes.font.lg,
  },
  profileDivider: {
    height: 1,
    marginVertical: adaptiveSizes.spacing.md,
  },
  routeList: {
    marginTop: adaptiveSizes.spacing.sm,
    marginBottom: adaptiveSizes.spacing.md,
    gap: adaptiveSizes.spacing.md,
    paddingHorizontal: adaptiveSizes.spacing.sm,
  },
  routeItem: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  routeLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: adaptiveSizes.spacing.md,
    flex: 1,
  },
  routeText: {
    fontSize: adaptiveSizes.font.lg,
    flexShrink: 1,
  },
  routeTime: {
    fontSize: adaptiveSizes.font.lg,
    fontWeight: '600',
  },
  dotGreen: {
    width: 12,
    height: 12,
    borderRadius: 6,
  },
  dotBlue: {
    width: 12,
    height: 12,
    borderRadius: 6,
  },
  bottomInfoRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: adaptiveSizes.spacing.lg,
    paddingHorizontal: adaptiveSizes.spacing.sm,
  },
  infoItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: adaptiveSizes.spacing.sm,
    opacity: 0.9,
  },
  infoText: {
    fontSize: adaptiveSizes.font.md,
    fontWeight: '600',
  },
  emptyState: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: adaptiveSizes.spacing.xxl * 2,
  },
  emptyStateIcon: {
    marginBottom: adaptiveSizes.spacing.lg,
  },
  emptyStateTitle: {
    fontSize: adaptiveSizes.font.xl,
    fontWeight: '600',
    textAlign: 'center',
  },
  emptyStateSubtitle: {
    fontSize: adaptiveSizes.font.md,
    marginTop: adaptiveSizes.spacing.sm,
    textAlign: 'center',
  },
});
