export const familyTypes = [
  { key: 'husband', label: 'Муж' },
  { key: 'wife', label: 'Жена' },
  { key: 'son', label: 'Сын' },
  { key: 'daughter', label: 'Дочь' },
  { key: 'mother', label: 'Мать' },
  { key: 'father', label: 'Отец' },
  { key: 'grandmother', label: 'Бабушка' },
  { key: 'grandfather', label: 'Дедушка' },
  { key: 'brother', label: 'Брат' },
  { key: 'sister', label: 'Сестра' },
  { key: 'uncle', label: 'Дядя' },
  { key: 'aunt', label: 'Тетя' },
  { key: 'cousin', label: 'Двоюродный брат/сестра' },
  { key: 'nephew', label: 'Племянник' },
  { key: 'niece', label: 'Племянница' },
  { key: 'stepfather', label: 'Отчим' },
  { key: 'stepmother', label: 'Мачеха' },
  { key: 'stepson', label: 'Пасынок' },
  { key: 'stepdaughter', label: 'Падчерица' },
  { key: 'other', label: 'Другое' },
]; 