import { StyleSheet } from "react-native";
import { getCurrentColors, SHADOWS, SIZES } from "../../../../constants/colors";

export const createSliderStyles = (isDark: boolean) => {
  const palette = getCurrentColors(isDark);

  return StyleSheet.create({
    sliderHandle: {
      width: 50,
      height: 5,
      backgroundColor: palette.border,
      borderRadius: 2.5,
      alignSelf: "center",
      marginTop: 0,
      marginBottom: SIZES.xs,
    },
    sliderHandleContainer: {
      width: 80,
      height: 30,
      alignItems: "center",
      justifyContent: "center",
      alignSelf: "center",
      marginTop: 0,
      marginBottom: SIZES.xs,
    },
    sliderBackgroundContainer: {
      position: "absolute",
      top: 0,
      left: 0,
      right: 0,
      bottom: 0,
      backgroundColor: "transparent",
      borderRadius: 50,
      justifyContent: "center",
      alignItems: "flex-end",
      paddingRight: 4,
      zIndex: 2,
    },
    sliderContainer: {
      width: "100%",
      height: 60,
      backgroundColor: palette.border,
      borderRadius: 30,
      justifyContent: "center",
      alignItems: "flex-end",
      paddingRight: 4,
    },
    sliderButton: {
      width: 60,
      height: 60,
      borderRadius: 30,
      backgroundColor: palette.primary,
      alignItems: "center",
      justifyContent: "center",
      zIndex: 3,
      ...(isDark ? SHADOWS.dark.medium : SHADOWS.light.medium),
    },
    smallCircle: {
      width: 30,
      height: 30,
      borderRadius: 15,
      backgroundColor: palette.primary,
      position: "absolute",
      right: -8,
      top: -26,
      zIndex: 2,
    },
    roundButton: {
      width: 60,
      height: 60,
      borderRadius: 30,
      backgroundColor: palette.primary,
      alignItems: "center",
      justifyContent: "center",
      marginLeft: 0,
      marginRight: -10,
      ...(isDark ? SHADOWS.dark.medium : SHADOWS.light.medium),
    },
    fixDriveContainer: {
      position: "absolute",
      top: 0,
      left: 0,
      right: 0,
      bottom: 0,
      alignItems: "center",
      justifyContent: "center",
      zIndex: 1,
    },
    fixDriveText: {
      fontSize: SIZES.fontSize.lg + 4,
      fontWeight: "700",
      color: palette.primary,
      letterSpacing: 1,
    },
    timerContainer: {
      flex: 1,
      alignItems: "center",
      justifyContent: "center",
    },
    timerText: {
      fontSize: SIZES.fontSize.xl + 8,
      fontWeight: "700",
      color: palette.primary,
      fontFamily: "monospace",
    },
  });
};
