import { Country } from "../../types/countries";

export const AFRICA: Country[] = [
  // === AFRICA ===
  {
    code: "DZ",
    name: "الجزائر", // Algeria
    flag: "🇩🇿",
    dialCode: "+213",
    format: "## ### ####",
    emergencyNumber: "14",
    currency: "DZD",
    timezone: "Africa/Algiers",
  },
  {
    code: "AO",
    name: "Angola",
    flag: "🇦🇴",
    dialCode: "+244",
    format: "### ### ###",
    emergencyNumber: "113",
    currency: "AOA",
    timezone: "Africa/Luanda",
  },
  {
    code: "BJ",
    name: "Bénin",
    flag: "🇧🇯",
    dialCode: "+229",
    format: "## ## ####",
    emergencyNumber: "117",
    currency: "XOF",
    timezone: "Africa/Porto-Novo",
  },
  {
    code: "BW",
    name: "Botswana",
    flag: "🇧🇼",
    dialCode: "+267",
    format: "## ### ###",
    emergencyNumber: "999",
    currency: "BWP",
    timezone: "Africa/Gaborone",
  },
  {
    code: "BF",
    name: "Burkina Faso",
    flag: "🇧🇫",
    dialCode: "+226",
    format: "## ## ####",
    emergencyNumber: "17",
    currency: "XOF",
    timezone: "Africa/Ouagadougou",
  },
  {
    code: "BI",
    name: "Uburundi",
    flag: "🇧🇮",
    dialCode: "+257",
    format: "## ## ####",
    emergencyNumber: "117",
    currency: "BIF",
    timezone: "Africa/Bujumbura",
  },
  {
    code: "CV",
    name: "Cabo Verde",
    flag: "🇨🇻",
    dialCode: "+238",
    format: "### ####",
    emergencyNumber: "132",
    currency: "CVE",
    timezone: "Atlantic/Cape_Verde",
  },
  {
    code: "CM",
    name: "Cameroun",
    flag: "🇨🇲",
    dialCode: "+237",
    format: "#### ####",
    emergencyNumber: "117",
    currency: "XAF",
    timezone: "Africa/Douala",
  },
  {
    code: "CF",
    name: "République centrafricaine",
    flag: "🇨🇫",
    dialCode: "+236",
    format: "## ## ####",
    emergencyNumber: "117",
    currency: "XAF",
    timezone: "Africa/Bangui",
  },
  {
    code: "TD",
    name: "Tchad",
    flag: "🇹🇩",
    dialCode: "+235",
    format: "## ## ## ##",
    emergencyNumber: "17",
    currency: "XAF",
    timezone: "Africa/Ndjamena",
  },
  {
    code: "KM",
    name: "Komori", // Comoros
    flag: "🇰🇲",
    dialCode: "+269",
    format: "## #####",
    emergencyNumber: "17",
    currency: "KMF",
    timezone: "Indian/Comoro",
  },
  {
    code: "CG",
    name: "Congo",
    flag: "🇨🇬",
    dialCode: "+242",
    format: "## ### ####",
    emergencyNumber: "117",
    currency: "XAF",
    timezone: "Africa/Brazzaville",
  },
  {
    code: "CD",
    name: "République démocratique du Congo",
    flag: "🇨🇩",
    dialCode: "+243",
    format: "## ### ####",
    emergencyNumber: "112",
    currency: "CDF",
    timezone: "Africa/Kinshasa",
  },
  {
    code: "CI",
    name: "Côte d’Ivoire",
    flag: "🇨🇮",
    dialCode: "+225",
    format: "## ## ## ##",
    emergencyNumber: "111",
    currency: "XOF",
    timezone: "Africa/Abidjan",
  },
  {
    code: "DJ",
    name: "جيبوتي", // Djibouti
    flag: "🇩🇯",
    dialCode: "+253",
    format: "## ## ## ##",
    emergencyNumber: "17",
    currency: "DJF",
    timezone: "Africa/Djibouti",
  },
  {
    code: "EG",
    name: "مصر", // Egypt
    flag: "🇪🇬",
    dialCode: "+20",
    format: "## #######",
    emergencyNumber: "122",
    currency: "EGP",
    timezone: "Africa/Cairo",
  },
  {
    code: "GQ",
    name: "Guinea Ecuatorial",
    flag: "🇬🇶",
    dialCode: "+240",
    format: "## ### ####",
    emergencyNumber: "113",
    currency: "XAF",
    timezone: "Africa/Malabo",
  },
  {
    code: "ER",
    name: "ኤርትራ", // Eritrea
    flag: "🇪🇷",
    dialCode: "+291",
    format: "## ### ###",
    emergencyNumber: "112",
    currency: "ERN",
    timezone: "Africa/Asmara",
  },
  {
    code: "ET",
    name: "ኢትዮጵያ", // Ethiopia
    flag: "🇪🇹",
    dialCode: "+251",
    format: "## ### ####",
    emergencyNumber: "991",
    currency: "ETB",
    timezone: "Africa/Addis_Ababa",
  },
  {
    code: "GA",
    name: "Gabon",
    flag: "🇬🇦",
    dialCode: "+241",
    format: "# ## ## ##",
    emergencyNumber: "1730",
    currency: "XAF",
    timezone: "Africa/Libreville",
  },
  {
    code: "GM",
    name: "Gambia",
    flag: "🇬🇲",
    dialCode: "+220",
    format: "### ####",
    emergencyNumber: "117",
    currency: "GMD",
    timezone: "Africa/Banjul",
  },
  {
    code: "GH",
    name: "Ghana",
    flag: "🇬🇭",
    dialCode: "+233",
    format: "## ### ####",
    emergencyNumber: "191",
    currency: "GHS",
    timezone: "Africa/Accra",
  },
  {
    code: "GN",
    name: "Guinée",
    flag: "🇬🇳",
    dialCode: "+224",
    format: "## ### ###",
    emergencyNumber: "122",
    currency: "GNF",
    timezone: "Africa/Conakry",
  },
  {
    code: "GW",
    name: "Guiné-Bissau",
    flag: "🇬🇼",
    dialCode: "+245",
    format: "### ####",
    emergencyNumber: "117",
    currency: "XOF",
    timezone: "Africa/Bissau",
  },
  {
    code: "KE",
    name: "Kenya",
    flag: "🇰🇪",
    dialCode: "+254",
    format: "### ### ###",
    emergencyNumber: "999",
    currency: "KES",
    timezone: "Africa/Nairobi",
  },
  {
    code: "LS",
    name: "Lesotho",
    flag: "🇱🇸",
    dialCode: "+266",
    format: "#### ####",
    emergencyNumber: "123",
    currency: "LSL",
    timezone: "Africa/Maseru",
  },
  {
    code: "LR",
    name: "Liberia",
    flag: "🇱🇷",
    dialCode: "+231",
    format: "## ### ###",
    emergencyNumber: "911",
    currency: "LRD",
    timezone: "Africa/Monrovia",
  },
  {
    code: "LY",
    name: "ليبيا", // Libya
    flag: "🇱🇾",
    dialCode: "+218",
    format: "##-###-####",
    emergencyNumber: "1515",
    currency: "LYD",
    timezone: "Africa/Tripoli",
  },
  {
    code: "MG",
    name: "Madagasikara",
    flag: "🇲🇬",
    dialCode: "+261",
    format: "## ## ####",
    emergencyNumber: "117",
    currency: "MGA",
    timezone: "Indian/Antananarivo",
  },
  {
    code: "MW",
    name: "Malawi",
    flag: "🇲🇼",
    dialCode: "+265",
    format: "1-###-###",
    emergencyNumber: "997",
    currency: "MWK",
    timezone: "Africa/Blantyre",
  },
  {
    code: "ML",
    name: "Mali",
    flag: "🇲🇱",
    dialCode: "+223",
    format: "## ## ####",
    emergencyNumber: "17",
    currency: "XOF",
    timezone: "Africa/Bamako",
  },
  {
    code: "MR",
    name: "موريتانيا", // Mauritania
    flag: "🇲🇷",
    dialCode: "+222",
    format: "## ## ## ##",
    emergencyNumber: "117",
    currency: "MRU",
    timezone: "Africa/Nouakchott",
  },
  {
    code: "MU",
    name: "Moris", // Mauritius (Creole)
    flag: "🇲🇺",
    dialCode: "+230",
    format: "### ####",
    emergencyNumber: "999",
    currency: "MUR",
    timezone: "Indian/Mauritius",
  },
  {
    code: "MA",
    name: "المغرب", // Morocco
    flag: "🇲🇦",
    dialCode: "+212",
    format: "## #######",
    emergencyNumber: "19",
    currency: "MAD",
    timezone: "Africa/Casablanca",
  },
  {
    code: "MZ",
    name: "Moçambique",
    flag: "🇲🇿",
    dialCode: "+258",
    format: "## ### ###",
    emergencyNumber: "119",
    currency: "MZN",
    timezone: "Africa/Maputo",
  },
  {
    code: "NA",
    name: "Namibia",
    flag: "🇳🇦",
    dialCode: "+264",
    format: "## ### ####",
    emergencyNumber: "10111",
    currency: "NAD",
    timezone: "Africa/Windhoek",
  },
  {
    code: "NE",
    name: "Niger",
    flag: "🇳🇪",
    dialCode: "+227",
    format: "## ## ####",
    emergencyNumber: "17",
    currency: "XOF",
    timezone: "Africa/Niamey",
  },
  {
    code: "NG",
    name: "Nigeria",
    flag: "🇳🇬",
    dialCode: "+234",
    format: "## ### ####",
    emergencyNumber: "112",
    currency: "NGN",
    timezone: "Africa/Lagos",
  },
  {
    code: "RW",
    name: "Rwanda",
    flag: "🇷🇼",
    dialCode: "+250",
    format: "### ### ###",
    emergencyNumber: "112",
    currency: "RWF",
    timezone: "Africa/Kigali",
  },
  {
    code: "ST",
    name: "São Tomé e Príncipe",
    flag: "🇸🇹",
    dialCode: "+239",
    format: "## #####",
    emergencyNumber: "112",
    currency: "STN",
    timezone: "Africa/Sao_Tome",
  },
  {
    code: "SN",
    name: "Sénégal",
    flag: "🇸🇳",
    dialCode: "+221",
    format: "## ### ####",
    emergencyNumber: "17",
    currency: "XOF",
    timezone: "Africa/Dakar",
  },
  {
    code: "SC",
    name: "Sesel", // Seychelles (Creole)
    flag: "🇸🇨",
    dialCode: "+248",
    format: "### ####",
    emergencyNumber: "999",
    currency: "SCR",
    timezone: "Indian/Mahe",
  },
  {
    code: "SL",
    name: "Sierra Leone",
    flag: "🇸🇱",
    dialCode: "+232",
    format: "## ######",
    emergencyNumber: "19",
    currency: "SLL",
    timezone: "Africa/Freetown",
  },
  {
    code: "SO",
    name: "Soomaaliya", // Somalia
    flag: "🇸🇴",
    dialCode: "+252",
    format: "## ### ###",
    emergencyNumber: "888",
    currency: "SOS",
    timezone: "Africa/Mogadishu",
  },
  {
    code: "ZA",
    name: "South Africa",
    flag: "🇿🇦",
    dialCode: "+27",
    format: "## ### ####",
    emergencyNumber: "10111",
    currency: "ZAR",
    timezone: "Africa/Johannesburg",
  },
  {
    code: "SS",
    name: "South Sudan",
    flag: "🇸🇸",
    dialCode: "+211",
    format: "## ### ###",
    emergencyNumber: "999",
    currency: "SSP",
    timezone: "Africa/Juba",
  },
  {
    code: "SD",
    name: "السودان", // Sudan
    flag: "🇸🇩",
    dialCode: "+249",
    format: "## ### ####",
    emergencyNumber: "999",
    currency: "SDG",
    timezone: "Africa/Khartoum",
  },
  {
    code: "SZ",
    name: "eSwatini",
    flag: "🇸🇿",
    dialCode: "+268",
    format: "## ## ####",
    emergencyNumber: "999",
    currency: "SZL",
    timezone: "Africa/Mbabane",
  },
  {
    code: "TZ",
    name: "Tanzania",
    flag: "🇹🇿",
    dialCode: "+255",
    format: "## ### ####",
    emergencyNumber: "112",
    currency: "TZS",
    timezone: "Africa/Dar_es_Salaam",
  },
  {
    code: "TG",
    name: "Togo",
    flag: "🇹🇬",
    dialCode: "+228",
    format: "## ### ###",
    emergencyNumber: "117",
    currency: "XOF",
    timezone: "Africa/Lome",
  },
  {
    code: "TN",
    name: "تونس", // Tunisia
    flag: "🇹🇳",
    dialCode: "+216",
    format: "## ### ###",
    emergencyNumber: "197",
    currency: "TND",
    timezone: "Africa/Tunis",
  },
  {
    code: "UG",
    name: "Uganda",
    flag: "🇺🇬",
    dialCode: "+256",
    format: "### ### ###",
    emergencyNumber: "112",
    currency: "UGX",
    timezone: "Africa/Kampala",
  },
  {
    code: "ZM",
    name: "Zambia",
    flag: "🇿🇲",
    dialCode: "+260",
    format: "## ### ###",
    emergencyNumber: "999",
    currency: "ZMW",
    timezone: "Africa/Lusaka",
  },
  {
    code: "ZW",
    name: "Zimbabwe",
    flag: "🇿🇼",
    dialCode: "+263",
    format: "## ### ####",
    emergencyNumber: "995",
    currency: "ZWL",
    timezone: "Africa/Harare",
  },
];
