import { StyleSheet, Platform } from "react-native";
import { getCurrentColors, SHADOWS, SIZES } from "../../constants/colors";

export const createChatScreenStyles = (isDark: boolean) => {
  const colors = getCurrentColors(isDark);
  return StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: colors.background,
    },
    header: {
      flexDirection: "row",
      alignItems: "center",
      marginHorizontal: SIZES.lg,
      paddingHorizontal: SIZES.lg,
      paddingVertical: SIZES.md,
      backgroundColor: colors.surface,
      borderBottomWidth: 1,
      borderBottomColor: colors.border,
      borderRadius: SIZES.radius.lg,
      overflow: "hidden",
      ...(isDark ? SHADOWS.dark.small : SHADOWS.light.small),
    },
    headerAvatar: {
      width: 40,
      height: 40,
      borderRadius: 20,
      backgroundColor: colors.primary,
      alignItems: "center",
      justifyContent: "center",
      marginRight: SIZES.md,
      position: "relative",
    },
    headerOnlineIndicator: {
      position: "absolute",
      bottom: 0,
      right: 0,
      width: 12,
      height: 12,
      borderRadius: 6,
      backgroundColor: "#10B981",
      borderWidth: 2,
      borderColor: colors.surface,
    },
    headerOfflineIndicator: {
      position: "absolute",
      bottom: 0,
      right: 0,
      width: 12,
      height: 12,
      borderRadius: 6,
      backgroundColor: "#9CA3AF",
      borderWidth: 2,
      borderColor: colors.surface,
    },
    headerInfo: {
      flex: 1,
    },
    headerName: {
      fontSize: SIZES.fontSize.lg,
      fontWeight: "600",
      color: colors.text,
    },
    headerStatus: {
      fontSize: SIZES.fontSize.sm,
      color: colors.textSecondary,
      marginTop: 2,
    },
    headerActions: {
      flexDirection: "row",
      alignItems: "center",
      gap: SIZES.sm,
    },
    headerButton: {
      padding: SIZES.sm,
      borderRadius: SIZES.radius.md,
    },
    messagesContent: {
      paddingHorizontal: SIZES.lg,
      paddingVertical: SIZES.md,
      flexGrow: 1,
    },
    messageContainer: {
      marginVertical: SIZES.sm,
      flexDirection: "row",
      alignItems: "flex-end",
    },
    userMessage: {
      justifyContent: "flex-end",
    },
    clientMessage: {
      justifyContent: "flex-start",
    },
    messageAvatar: {
      width: 32,
      height: 32,
      borderRadius: 16,
      marginRight: SIZES.sm,
      backgroundColor: colors.primary,
      alignItems: "center",
      justifyContent: "center",
    },
    messageBubble: {
      maxWidth: "80%",
      borderRadius: SIZES.radius.lg,
      paddingHorizontal: SIZES.lg,
      paddingVertical: SIZES.md,
      backgroundColor: colors.primary,
      ...Platform.select({
        ios: {
          shadowColor: "#000",
          shadowOffset: { width: 0, height: 1 },
          shadowOpacity: 0.1,
          shadowRadius: 3,
        },
        android: {
          elevation: 3,
        },
      }),
    },
    messageText: {
      fontSize: SIZES.fontSize.md,
      lineHeight: SIZES.lineHeight.lg,
      color: colors.background,
    },
    otherMessage: {
      backgroundColor: isDark ? "#374151" : "#F3F4F6",
      borderWidth: 1,
      borderColor: colors.border,
    },
    otherMessageText: {
      color: colors.text,
    },
    messageTime: {
      fontSize: SIZES.fontSize.xs,
      color: isDark ? "#9CA3AF" : "#6B7280",
      marginTop: SIZES.xs,
      alignSelf: "flex-end",
    },
    messageStatus: {
      flexDirection: "row",
      alignItems: "center",
      marginTop: SIZES.xs,
      alignSelf: "flex-end",
    },
    statusIcon: {
      marginLeft: SIZES.xs,
    },
    typingIndicator: {
      flexDirection: "row",
      alignItems: "center",
      paddingHorizontal: SIZES.lg,
      paddingVertical: SIZES.sm,
    },
    typingText: {
      fontSize: SIZES.fontSize.sm,
      color: colors.textSecondary,
      fontStyle: "italic",
    },
    inputAvoider: {
      backgroundColor: "transparent",
    },
    inputContainer: {
      marginHorizontal: SIZES.lg,
      marginBottom: SIZES.md,
      paddingHorizontal: SIZES.lg,
      paddingTop: SIZES.sm,
      paddingBottom: Platform.OS === "ios" ? SIZES.lg : SIZES.sm,
      backgroundColor: colors.surface,
      borderWidth: 1,
      borderColor: colors.border,
      borderRadius: SIZES.radius.lg,
      ...(isDark ? SHADOWS.dark.small : SHADOWS.light.small),
    },
    inputRow: {
      flexDirection: "row",
      alignItems: "flex-end",
      gap: SIZES.sm,
    },
    toolbarButton: {
      width: 44,
      height: 44,
      borderRadius: 22,
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: colors.background,
      borderWidth: 1,
      borderColor: colors.border,
    },
    textInput: {
      flex: 1,
      borderRadius: 22,
      paddingHorizontal: SIZES.lg,
      paddingVertical: SIZES.md,
      fontSize: SIZES.fontSize.md,
      maxHeight: 120,
      minHeight: 44,
      borderWidth: 1,
      borderColor: colors.border,
      backgroundColor: colors.background,
      color: colors.text,
    },
    sendButton: {
      width: 44,
      height: 44,
      borderRadius: 22,
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: colors.primary,
      ...(isDark ? SHADOWS.dark.small : SHADOWS.light.small),
    },
    sendIcon: {
      color: colors.background,
    },
    attachmentMenu: {
      position: "absolute",
      bottom: 80,
      left: 0,
      backgroundColor: colors.surface,
      borderRadius: SIZES.radius.lg,
      borderWidth: 1,
      borderColor: colors.border,
      padding: SIZES.sm,
      ...(isDark ? SHADOWS.dark.medium : SHADOWS.light.medium),
    },
    attachmentOption: {
      flexDirection: "row",
      alignItems: "center",
      paddingVertical: SIZES.sm,
      paddingHorizontal: SIZES.md,
      borderRadius: SIZES.radius.md,
    },
    attachmentOptionText: {
      marginLeft: SIZES.sm,
      fontSize: SIZES.fontSize.md,
      color: colors.text,
    },
    callSheetOverlay: {
      position: "absolute",
      left: 0,
      right: 0,
      top: 0,
      bottom: 0,
      justifyContent: "flex-end",
    },
    callSheetBackdrop: {
      position: "absolute",
      left: 0,
      right: 0,
      top: 0,
      bottom: 0,
      backgroundColor: isDark ? "rgba(0,0,0,0.6)" : "rgba(0,0,0,0.4)",
    },
    callSheetContainer: {
      backgroundColor: colors.surface,
      borderTopLeftRadius: SIZES.radius.xl,
      borderTopRightRadius: SIZES.radius.xl,
      borderWidth: 1,
      borderColor: colors.border,
      paddingHorizontal: SIZES.lg,
      paddingTop: SIZES.md,
      paddingBottom: SIZES.xl,
      ...(isDark ? SHADOWS.dark.large : SHADOWS.light.large),
    },
    // Profile sheet header layout
    profileHeaderRow: {
      flexDirection: "row",
      alignItems: "center",
      gap: SIZES.md,
      paddingHorizontal: SIZES.sm,
      marginTop: SIZES.md,
      marginBottom: SIZES.md,
    },
    profileAvatarLarge: {
      width: 56,
      height: 56,
      borderRadius: 28,
      backgroundColor: colors.primary,
      alignItems: "center",
      justifyContent: "center",
      position: "relative",
    },
    profileInfo: {
      flex: 1,
    },
    profileNameRow: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      gap: SIZES.md,
    },
    profileName: {
      fontSize: SIZES.fontSize.xxl,
      fontWeight: "700",
      color: colors.text,
      marginBottom: 2,
    },
    profileSubline: {
      fontSize: SIZES.fontSize.md,
      color: colors.textSecondary,
    },
    profileStatusRow: {
      flexDirection: "row",
      alignItems: "center",
      gap: SIZES.xs,
      marginTop: SIZES.sm,
    },
    statusDotOnline: {
      width: 10,
      height: 10,
      borderRadius: 5,
      backgroundColor: "#10B981",
    },
    statusDotOffline: {
      width: 10,
      height: 10,
      borderRadius: 5,
      backgroundColor: "#9CA3AF",
    },
    profileStatusText: {
      fontSize: SIZES.fontSize.md,
      color: colors.textSecondary,
    },
    profileRating: {
      paddingHorizontal: SIZES.sm,
      paddingVertical: SIZES.xs,
      borderRadius: SIZES.radius.md,
      backgroundColor: isDark ? "#08319822" : "#10B9811A",
      alignSelf: "flex-start",
    },
    profileRatingText: {
      color: "#10B981",
      fontWeight: "700",
      fontSize: SIZES.fontSize.lg,
    },
    profileDivider: {
      height: 1,
      backgroundColor: colors.border,
      marginVertical: SIZES.md,
    },
    routeList: {
      marginTop: SIZES.sm,
      marginBottom: SIZES.md,
      gap: SIZES.md,
      paddingHorizontal: SIZES.sm,
    },
    routeItem: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
    },
    routeLeft: {
      flexDirection: "row",
      alignItems: "center",
      gap: SIZES.md,
      flex: 1,
    },
    routeText: {
      fontSize: SIZES.fontSize.lg,
      color: colors.text,
      flexShrink: 1,
    },
    routeTime: {
      fontSize: SIZES.fontSize.lg,
      color: colors.textSecondary,
      fontWeight: "600",
    },
    dotGreen: {
      width: 12,
      height: 12,
      borderRadius: 6,
      backgroundColor: "#10B981",
    },
    dotBlue: {
      width: 12,
      height: 12,
      borderRadius: 6,
      backgroundColor: "#3B82F6",
    },
    bottomInfoRow: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      marginTop: SIZES.lg,
      paddingHorizontal: SIZES.sm,
    },
    infoItem: {
      flexDirection: "row",
      alignItems: "center",
      gap: SIZES.sm,
      opacity: 0.9,
    },
    infoText: {
      fontSize: SIZES.fontSize.md,
      color: colors.textSecondary,
      fontWeight: "600",
    },
    callSheetClose: {
      position: "absolute",
      top: SIZES.md,
      right: SIZES.md,
      padding: SIZES.sm,
      borderRadius: SIZES.radius.md,
    },
    callSheetHandle: {
      alignSelf: "center",
      width: 40,
      height: 4,
      borderRadius: 2,
      backgroundColor: colors.border,
      marginBottom: SIZES.md,
    },
    callSheetTitle: {
      fontSize: SIZES.fontSize.xl,
      fontWeight: "600",
      color: colors.text,
      marginBottom: SIZES.md,
      textAlign: "center",
    },
    callSheetOption: {
      flexDirection: "row",
      alignItems: "center",
      gap: SIZES.md,
      backgroundColor: colors.background,
      borderRadius: SIZES.radius.lg,
      paddingHorizontal: SIZES.lg,
      paddingVertical: SIZES.md,
      borderWidth: 1,
      borderColor: colors.border,
      marginTop: SIZES.sm,
    },
    callSheetOptionText: {
      fontSize: SIZES.fontSize.md,
      color: colors.text,
    },
    callSheetCancel: {
      marginTop: SIZES.lg,
      alignSelf: "center",
      paddingVertical: SIZES.sm,
      paddingHorizontal: SIZES.xl,
      borderRadius: SIZES.radius.md,
      backgroundColor: "transparent",
    },
    callSheetCancelText: {
      fontSize: SIZES.fontSize.lg,
      color: colors.textSecondary,
    },
    emptyState: {
      flex: 1,
      alignItems: "center",
      justifyContent: "center",
      paddingVertical: SIZES.xxl * 2,
    },
    emptyStateIcon: {
      marginBottom: SIZES.lg,
    },
    emptyStateTitle: {
      fontSize: SIZES.fontSize.xl,
      fontWeight: "600",
      color: colors.text,
      textAlign: "center",
    },
    emptyStateSubtitle: {
      fontSize: SIZES.fontSize.md,
      color: colors.textSecondary,
      marginTop: SIZES.sm,
      textAlign: "center",
    },
  });
};
