import { StyleSheet } from 'react-native';
import { getCurrentColors, SIZES } from '../../constants/colors';

export const createOrdersMapScreenStyles = (isDark: boolean) => {
  const colors = getCurrentColors(isDark);
  return StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: colors.background,
      paddingTop: 0, // Убираем верхний отступ SafeAreaView
    },
    mapContainer: {
      flex: 1,
      position: 'relative',
    },
    topLeftButton: {
      position: 'absolute',
      top: SIZES.xl + 32,
      left: SIZES.lg,
      width: 48,
      height: 48,
      borderRadius: 24,
      backgroundColor: colors.background,
      borderWidth: 1,
      borderColor: colors.border,
      alignItems: 'center',
      justifyContent: 'center',
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 4,
      elevation: 4,
      zIndex: 10,
    },
    topRightButton: {
      position: 'absolute',
      top: SIZES.xl + 32,
      right: SIZES.lg,
      width: 48,
      height: 48,
      borderRadius: 24,
      backgroundColor: colors.background,
      borderWidth: 1,
      borderColor: colors.border,
      alignItems: 'center',
      justifyContent: 'center',
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 4,
      elevation: 4,
      zIndex: 10,
    },
    sosText: {
      fontSize: 12,
      fontWeight: '700',
      color: '#DC2626',
      letterSpacing: 1,
    },
    bottomButtonsContainer: {
      position: 'absolute',
      bottom: SIZES.xl,
      right: SIZES.lg - 4,
      flexDirection: 'column',
      alignItems: 'flex-end',
      gap: SIZES.md,
    },
    bottomButton: {
      width: 48,
      height: 48,
      borderRadius: 24,
      backgroundColor: colors.background,
      alignItems: 'center',
      justifyContent: 'center',
      borderWidth: 1,
      borderColor: colors.border,
      shadowColor: '#000',
      shadowOffset: {
        width: 0,
        height: 2,
      },
      shadowOpacity: 0.1,
      shadowRadius: 4,
      elevation: 4,
    },
    settingsPanel: {
      position: 'absolute',
      bottom: 60,
      right: 0,
      backgroundColor: 'transparent',
      borderRadius: SIZES.radius.lg,
      borderWidth: 0,
      borderColor: 'transparent',
      padding: 0,
      shadowColor: 'transparent',
      shadowOffset: {
        width: 0,
        height: 0,
      },
      shadowOpacity: 0,
      shadowRadius: 0,
      elevation: 0,
      flexDirection: 'column',
      alignItems: 'flex-end',
      gap: SIZES.xs,
      width: 48, // Ограничиваем ширину панели
      height: 300, // Ограничиваем высоту панели
      pointerEvents: 'box-none', // Позволяет кликам проходить сквозь панель, но кнопки остаются кликабельными
    },
    settingsButton: {
      alignItems: 'center',
      justifyContent: 'center',
      paddingVertical: SIZES.xs,
      paddingHorizontal: SIZES.xs,
      borderRadius: 24, // Делаем круглую форму как у основных кнопок
      width: 48,
      height: 48,
      backgroundColor: colors.background,
      borderWidth: 1,
      borderColor: colors.border,
      shadowColor: '#000',
      shadowOffset: {
        width: 0,
        height: 2,
      },
      shadowOpacity: 0.1,
      shadowRadius: 4,
      elevation: 4,
      pointerEvents: 'auto', // Кнопки остаются кликабельными
    },
    settingsButtonText: {
      fontSize: SIZES.fontSize.md,
      color: colors.text,
      fontWeight: '500',
      marginLeft: SIZES.sm,
    },
    
    // Стили для модалки репорта
    reportModalOverlay: {
      flex: 1,
      backgroundColor: 'rgba(0, 0, 0, 0.5)',
      justifyContent: 'center',
      alignItems: 'center',
    },
    reportModalContainer: {
      backgroundColor: colors.background,
      borderRadius: SIZES.radius.xl,
      padding: SIZES.xl,
      marginHorizontal: SIZES.lg,
      minWidth: 320,
      maxWidth: 400,
      shadowColor: '#000',
      shadowOffset: {
        width: 0,
        height: 4,
      },
      shadowOpacity: 0.25,
      shadowRadius: 8,
      elevation: 8,
    },
    reportModalHeader: {
      alignItems: 'center',
      marginBottom: SIZES.lg,
    },
    reportIconContainer: {
      width: 64,
      height: 64,
      borderRadius: 32,
      backgroundColor: '#FEF2F2',
      alignItems: 'center',
      justifyContent: 'center',
      marginBottom: SIZES.md,
    },
    reportModalTitle: {
      fontSize: SIZES.fontSize.xl,
      fontWeight: '700',
      color: colors.text,
      textAlign: 'center',
    },
    reportModalSubtitle: {
      fontSize: SIZES.fontSize.md,
      color: colors.textSecondary,
      textAlign: 'center',
      marginBottom: SIZES.lg,
    },
    reportCommentInput: {
      borderWidth: 1,
      borderColor: colors.border,
      borderRadius: SIZES.radius.md,
      padding: SIZES.md,
      fontSize: SIZES.fontSize.md,
      color: colors.text,
      backgroundColor: colors.surface,
      minHeight: 100,
      marginBottom: SIZES.xl,
      textAlignVertical: 'top',
    },
    reportModalButtons: {
      flexDirection: 'row',
      gap: SIZES.md,
    },
    reportCancelButton: {
      flex: 1,
      paddingVertical: SIZES.md,
      paddingHorizontal: SIZES.lg,
      borderRadius: SIZES.radius.md,
      borderWidth: 1,
      borderColor: colors.border,
      backgroundColor: 'transparent',
      alignItems: 'center',
    },
    reportCancelButtonText: {
      fontSize: SIZES.fontSize.md,
      fontWeight: '600',
      color: colors.text,
    },
    reportSubmitButton: {
      flex: 1,
      paddingVertical: SIZES.md,
      paddingHorizontal: SIZES.lg,
      borderRadius: SIZES.radius.md,
      backgroundColor: '#DC2626',
      alignItems: 'center',
    },
    reportSubmitButtonDisabled: {
      backgroundColor: colors.border,
      borderWidth: 1,
      borderColor: colors.border,
    },
    reportSubmitButtonText: {
      fontSize: SIZES.fontSize.md,
      fontWeight: '600',
      color: '#FFFFFF',
    },
    reportSubmitButtonTextDisabled: {
      color: colors.textSecondary,
    },
    leftButton: {
      position: 'absolute',
      bottom: SIZES.xl,
      left: SIZES.lg - 4,
      width: 48,
      height: 48,
      borderRadius: 24,
      backgroundColor: colors.background,
      alignItems: 'center',
      justifyContent: 'center',
      borderWidth: 1,
      borderColor: colors.border,
      shadowColor: '#000',
      shadowOffset: {
        width: 0,
        height: 2,
      },
      shadowOpacity: 0.1,
      shadowRadius: 4,
      elevation: 4,
    },
    
    // Стили для простого диалога
    simpleDialogOverlay: {
      flex: 1,
      backgroundColor: 'rgba(0, 0, 0, 0.5)',
      justifyContent: 'center',
      alignItems: 'center',
    },
    simpleDialogContainer: {
      backgroundColor: colors.background,
      borderRadius: SIZES.radius.lg,
      padding: SIZES.xl,
      margin: SIZES.xl,
      minWidth: 280,
      shadowColor: '#000',
      shadowOffset: {
        width: 0,
        height: 4,
      },
      shadowOpacity: 0.25,
      shadowRadius: 8,
      elevation: 8,
    },
    simpleDialogTitle: {
      fontSize: SIZES.fontSize.xl,
      fontWeight: '700',
      color: colors.text,
      textAlign: 'center',
      marginBottom: SIZES.md,
    },
    simpleDialogMessage: {
      fontSize: SIZES.fontSize.md,
      color: colors.textSecondary,
      textAlign: 'center',
      marginBottom: SIZES.xl,
    },
    simpleDialogButtons: {
      flexDirection: 'row',
      gap: SIZES.md,
    },
    simpleDialogNoButton: {
      flex: 1,
      paddingVertical: SIZES.md,
      paddingHorizontal: SIZES.lg,
      borderRadius: SIZES.radius.md,
      borderWidth: 1,
      borderColor: colors.border,
      backgroundColor: 'transparent',
      alignItems: 'center',
    },
    simpleDialogNoButtonText: {
      fontSize: SIZES.fontSize.md,
      fontWeight: '600',
      color: colors.text,
    },
    simpleDialogYesButton: {
      flex: 1,
      paddingVertical: SIZES.md,
      paddingHorizontal: SIZES.lg,
      borderRadius: SIZES.radius.md,
      backgroundColor: colors.primary,
      alignItems: 'center',
    },
    simpleDialogYesButtonText: {
      fontSize: SIZES.fontSize.md,
      fontWeight: '600',
      color: '#FFFFFF',
    },
  });
};


