name: Deploy

on:
  push:
    branches: [ main ]
  workflow_run:
    workflows: ["Tests"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event.workflow_run.conclusion == 'success'

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'

    - name: Install dependencies
      run: npm install --legacy-peer-deps

    - name: Install Expo CLI
      run: npm install -g @expo/cli

    - name: Build for web
      run: npm run web:build
      env:
        NODE_ENV: production

    - name: Deploy to Expo
      run: |
        echo "Deploying to Expo..."
        # npx expo publish --release-channel production
        # или для EAS:
        # npx eas build --platform all --non-interactive
      env:
        EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}

    - name: Notify deployment
      run: echo "Deployment completed successfully" 