import { StyleSheet } from 'react-native';
import { SIZES, SHADOWS, colors } from '../../../shared/constants/adaptiveConstants';

export const DriverRegisterScreenStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#FFFFFF',
  },
  scrollContent: {
    flexGrow: 1,
    padding: SIZES.lg,
    paddingBottom: 40,
  },
  header: {
    alignItems: 'center',
    marginBottom: SIZES.xl,
    position: 'relative',
  },
  backButton: {
    position: 'absolute',
    left: -24,
    top: 0,
    padding: 8,
    zIndex: 2,
  },
  title: {
    fontSize: 28,
    fontWeight: '700',
    color: '#1E293B',
    marginBottom: SIZES.sm,
    textAlign: 'center',
  },
  subtitle: {
    fontSize: 16,
    color: '#64748B',
    textAlign: 'center',
    marginBottom: SIZES.lg,
  },
  languageContainer: {
    marginBottom: SIZES.xl,
  },
  languageButton: {
    backgroundColor: '#F8FAFC',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    paddingHorizontal: SIZES.lg,
    paddingVertical: SIZES.md,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    minHeight: 48,
    ...SHADOWS.light.small,
  },
  languageButtonText: {
    fontSize: 16,
    color: '#1E293B',
    flex: 1,
    marginLeft: SIZES.sm,
  },
  form: {
    flex: 1,
  },
  section: {
    marginBottom: SIZES.xl,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: '#1E293B',
    marginBottom: SIZES.lg,
    paddingBottom: SIZES.sm,
    borderBottomWidth: 1,
    borderBottomColor: '#E2E8F0',
  },
  inputContainer: {
    marginBottom: SIZES.lg,
  },
  label: {
    fontSize: 16,
    fontWeight: '600',
    color: '#1E293B',
    marginBottom: SIZES.sm,
  },
  input: {
    backgroundColor: '#F8FAFC',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    paddingHorizontal: SIZES.lg,
    paddingVertical: SIZES.md,
    fontSize: 16,
    color: '#1E293B',
    minHeight: 48,
    ...SHADOWS.light.small,
  },
  inputError: {
    borderColor: '#EF4444',
    borderWidth: 2,
  },
  errorText: {
    fontSize: 14,
    color: '#EF4444',
    marginTop: SIZES.xs,
    marginLeft: SIZES.sm,
  },
  selectContainer: {
    backgroundColor: '#F8FAFC',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    paddingHorizontal: SIZES.lg,
    paddingVertical: SIZES.md,
    minHeight: 48,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    ...SHADOWS.light.small,
  },
  selectText: {
    fontSize: 16,
    color: '#1E293B',
    flex: 1,
  },
  photoSection: {
    marginBottom: SIZES.lg,
  },
  photoUpload: {
    backgroundColor: '#F1F5F9',
    borderRadius: 12,
    borderWidth: 2,
    borderColor: '#CBD5E1',
    borderStyle: 'dashed',
    padding: SIZES.xl,
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: 150,
  },
  photoText: {
    fontSize: 16,
    color: '#64748B',
    marginTop: SIZES.sm,
    textAlign: 'center',
  },
  passwordContainer: {
    position: 'relative',
  },
  passwordInput: {
    backgroundColor: '#F8FAFC',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    paddingHorizontal: SIZES.lg,
    paddingVertical: SIZES.md,
    paddingRight: 60,
    fontSize: 16,
    color: '#1E293B',
    minHeight: 48,
    ...SHADOWS.light.small,
  },
  eyeButton: {
    position: 'absolute',
    right: SIZES.md,
    top: '50%',
    transform: [{ translateY: -10 }],
    padding: 8,
    borderRadius: 20,
    backgroundColor: '#F1F5F9',
    borderWidth: 1,
    borderColor: '#E2E8F0',
  },
  agreementContainer: {
    marginBottom: SIZES.xl,
  },
  checkboxContainer: {
    flexDirection: 'row',
    alignItems: 'flex-start',
  },
  checkbox: {
    width: 24,
    height: 24,
    borderRadius: 6,
    borderWidth: 2,
    borderColor: '#CBD5E1',
    marginRight: SIZES.md,
    marginTop: 2,
    alignItems: 'center',
    justifyContent: 'center',
  },
  checkboxChecked: {
    backgroundColor: '#3B82F6',
    borderColor: '#3B82F6',
  },
  agreementText: {
    fontSize: 14,
    color: '#64748B',
    flex: 1,
    lineHeight: 20,
  },
  agreementLink: {
    color: '#3B82F6',
    textDecorationLine: 'underline',
    fontWeight: '600',
  },
  registerButton: {
    backgroundColor: '#3B82F6',
    borderRadius: 12,
    paddingVertical: SIZES.lg,
    paddingHorizontal: SIZES.xl,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: SIZES.lg,
    ...SHADOWS.light.medium,
  },
  registerButtonText: {
    color: '#FFFFFF',
    fontSize: 18,
    fontWeight: '600',
  },
  loginContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: SIZES.xl,
  },
  loginText: {
    fontSize: 16,
    color: '#64748B',
  },
  loginLink: {
    fontSize: 16,
    color: '#3B82F6',
    fontWeight: '600',
    textDecorationLine: 'underline',
  },
});
